name: CI

on: [push]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Number of commits to fetch. 0 indicates all history.
        # jgit task nested in customBuild.xml fails without history.
        fetch-depth: '1'
    - name: Update tags
      run: |
           wget https://nightly.tlapl.us/products/TLAToolbox-1.7.1-macosx.cocoa.x86_64.zip
           xcrun altool --notarize-app --primary-bundle-id "org.lamport.tla.toolbox.product.product" --username "${{secrets.APPLE_CODESIGN_DEVELOPER_ID}}" --password "${{secrets.APPLE_CODESIGN_DEVELOPER_PASSWORD}}" --file "TLAToolbox-1.7.1-macosx.cocoa.x86_64.zip"
           